### ISSUE TITLE
Global single post template

### ISSUE THREAD

**Issue by toton333** [wpPlugins-io/Press-Elements#2]
Hi, thank you for this nice plugin. Can i create a single post template with press elements and elementor and it can be applied globally to all single post style? Just like elementor pro, you create a single page template you set the condition to all posts and it applies to all posts, instead of going to each post and apply the template individually.

**Comment by ramiy** [comment]
Hi @toton333 ,

Press-Elements adds widgets that return theme components (title, excerpt, feature images and others), it's not a theme builder. You can use those widgets to create reusable templates and apply them to your individual posts, but not to all your posts.
